version: "3.9"

services:
  proxy:
    image: httpd:2.4
    container_name: team2-apache
    ports:
      - "80:80"         # add "443:443" if using https.conf later
    volumes:
      - ./apache/httpd.conf:/usr/local/apache2/conf/httpd.conf:ro
      - ./apache/team2.conf:/usr/local/apache2/conf/extra/team2.conf:ro
      # - ./apache/https.conf:/usr/local/apache2/conf/extra/https.conf:ro
      # - ./apache/certs:/usr/local/apache2/conf/certs:ro
    networks:
      appnet:
        aliases: ["team2-apache"]
    depends_on:
      - team2-app
      - team2-jupyter

  team2-app:
    build: ./team2-app
    container_name: team2-app
    expose:
      - "2502"
    networks:
      appnet:
        aliases: ["team2-app"]

  team2-jupyter:
    image: jupyter/base-notebook:python-3.11
    container_name: team2-jupyter
    command:
      - start-notebook.sh
      - --ServerApp.base_url=/team2/jupyter
      - --ServerApp.trust_xheaders=True
      - --ServerApp.ip=0.0.0.0
      - --ServerApp.port=8888
      - --ServerApp.token=
      - --ServerApp.password=
    environment:
      - JUPYTER_ENABLE_LAB=yes
    volumes:
      - ./team2-notebooks:/home/jovyan/team2/notebooks
    expose:
      - "8888"
    networks:
      appnet:
        aliases: ["team2-jupyter"]

networks:
  appnet:
    driver: bridge
