services:
  team2-app:
    build: .
    container_name: team2-app
    expose: ["2502"]           # Streamlit listens on 2502 inside container
    networks: [appnet]

  team2-jupyter:
    image: jupyter/base-notebook:latest
    container_name: team2-jupyter
    command:
      - start-notebook.sh
      - --ServerApp.base_url=/team2f25/jupyter/
      - --ServerApp.token=
      - --ServerApp.password=
    environment:
      - JUPYTER_ENABLE_LAB=yes
    expose: ["8888"]
    networks: [appnet]

  team2-apache:
    image: httpd:2.4
    container_name: team2-apache
    ports: ["2502:80"]
    volumes:
      - ./apache/httpd.conf:/usr/local/apache2/conf/httpd.conf:ro
      - ./apache/team2.conf:/usr/local/apache2/conf/extra/team2.conf:ro
    depends_on: [team2-app, team2-jupyter]
    networks: [appnet]

networks:
  appnet:
    driver: bridge
