services:
  proxy:
    image: httpd:2.4
    container_name: team2-apache
    ports:
      - "2502:80"        # was 8080:80 or 80:80
    volumes:
      - ./apache/httpd.conf:/usr/local/apache2/conf/httpd.conf:ro
      - ./apache/team2.conf:/usr/local/apache2/conf/extra/team2.conf:ro
    depends_on:
      - team2-app
      - team2-jupyter
    networks:
      appnet:
        aliases: ["team2-apache"]

  team2-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: team2-app
    expose:
      - "2502"
    networks:
      appnet:
        aliases: ["team2-app"]

  team2-jupyter:
    image: jupyter/base-notebook:python-3.11
    container_name: team2-jupyter
    command:
      - start-notebook.sh
      - --ServerApp.base_url=/team2f25/jupyter
      - --ServerApp.trust_xheaders=True
      - --ServerApp.ip=0.0.0.0
      - --ServerApp.port=8888
      - --ServerApp.token=
      - --ServerApp.password=
    environment:
      - JUPYTER_ENABLE_LAB=yes
    volumes:
      - ./team2-notebooks:/home/jovyan/team2/notebooks
    expose:
      - "8888"
    networks:
      appnet:
        aliases: ["team2-jupyter"]

networks:
  appnet:
    driver: bridge
