[server]
address = "0.0.0.0"
port = 5002
# Use this when deployed behind the CSUSB reverse proxy.
# For local dev you can override with env: STREAMLIT_SERVER_BASE_URL_PATH=""
baseUrlPath = "team2f25"
headless = true
enableCORS = false
enableXsrfProtection = true

[theme]
base = "light"
